/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReplyTokenRouteImport } from './routes/reply.$token'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdReportRouteImport } from './routes/projects.$projectId.report'
import { Route as ProjectsProjectIdExtractRouteImport } from './routes/projects.$projectId.extract'
import { Route as ProjectsProjectIdAgentRouteImport } from './routes/projects.$projectId.agent'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyTokenRoute = ReplyTokenRouteImport.update({
  id: '/reply/$token',
  path: '/reply/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdReportRoute = ProjectsProjectIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdExtractRoute =
  ProjectsProjectIdExtractRouteImport.update({
    id: '/extract',
    path: '/extract',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdAgentRoute = ProjectsProjectIdAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/reply/$token': typeof ReplyTokenRoute
  '/projects/$projectId/agent': typeof ProjectsProjectIdAgentRoute
  '/projects/$projectId/extract': typeof ProjectsProjectIdExtractRoute
  '/projects/$projectId/report': typeof ProjectsProjectIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/reply/$token': typeof ReplyTokenRoute
  '/projects/$projectId/agent': typeof ProjectsProjectIdAgentRoute
  '/projects/$projectId/extract': typeof ProjectsProjectIdExtractRoute
  '/projects/$projectId/report': typeof ProjectsProjectIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/reply/$token': typeof ReplyTokenRoute
  '/projects/$projectId/agent': typeof ProjectsProjectIdAgentRoute
  '/projects/$projectId/extract': typeof ProjectsProjectIdExtractRoute
  '/projects/$projectId/report': typeof ProjectsProjectIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/reply/$token'
    | '/projects/$projectId/agent'
    | '/projects/$projectId/extract'
    | '/projects/$projectId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/reply/$token'
    | '/projects/$projectId/agent'
    | '/projects/$projectId/extract'
    | '/projects/$projectId/report'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/reply/$token'
    | '/projects/$projectId/agent'
    | '/projects/$projectId/extract'
    | '/projects/$projectId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReplyTokenRoute: typeof ReplyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply/$token': {
      id: '/reply/$token'
      path: '/reply/$token'
      fullPath: '/reply/$token'
      preLoaderRoute: typeof ReplyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/report': {
      id: '/projects/$projectId/report'
      path: '/report'
      fullPath: '/projects/$projectId/report'
      preLoaderRoute: typeof ProjectsProjectIdReportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/extract': {
      id: '/projects/$projectId/extract'
      path: '/extract'
      fullPath: '/projects/$projectId/extract'
      preLoaderRoute: typeof ProjectsProjectIdExtractRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/agent': {
      id: '/projects/$projectId/agent'
      path: '/agent'
      fullPath: '/projects/$projectId/agent'
      preLoaderRoute: typeof ProjectsProjectIdAgentRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAgentRoute: typeof ProjectsProjectIdAgentRoute
  ProjectsProjectIdExtractRoute: typeof ProjectsProjectIdExtractRoute
  ProjectsProjectIdReportRoute: typeof ProjectsProjectIdReportRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAgentRoute: ProjectsProjectIdAgentRoute,
  ProjectsProjectIdExtractRoute: ProjectsProjectIdExtractRoute,
  ProjectsProjectIdReportRoute: ProjectsProjectIdReportRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReplyTokenRoute: ReplyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
